package com.inno.serialport.utilities.profile

const val LEFT_BREWER_ID = 1000
const val RIGHT_BREWER_ID = 1001
const val LEFT_BOILER_ID = 2000
const val RIGHT_BOILER_ID = 2001
const val STEAM_BOILER_ID = 2002
const val FRONT_GRINDER_ID = 3000
const val BACK_GRINDER_ID = 3001
const val WATER_INPUT_VALVE_ID = 4000
const val LEFT_VALVE_LEFT_BOILER_ID = 4001
const val MIDILE_VALVE_LEFT_BOILER_ID = 4002
const val RIGHT_VALVE_LEFT_BOILER_ID = 4003
const val LEFT_VALVE_RIGHT_BOILER_ID = 4004
const val MIDILE_VALVE_RIGHT_BOILER_ID = 4005
const val RIGHT_VALVE_RIGHT_BOILER_ID = 4006
const val WATER_INPUT_PUMP_ID = 5000
const val AIR_INPUT_PUMP_ID = 5100