/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inno_serialport_SerialPortJava */

#ifndef _Included_com_inno_serialport_SerialPortJava
#define _Included_com_inno_serialport_SerialPortJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_inno_serialport_SerialPortJava
 * Method:    open
 * Signature: (Ljava/lang/String;IIIII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_inno_serialport_SerialPortJava_open
        (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_inno_serialport_SerialPortJava
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_inno_serialport_SerialPortJava_close
        (JNIEnv *, jobject);

/*
 * Class:     com_inno_serialport_SerialPortJava
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_inno_serialport_SerialPortJava_test
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
