package com.inno.coffee.utilities

const val LOCK_AND_CLEAN_TIME = 15
const val VIEW_FAST_CLICK_INTERVAL_TIME = 300
const val DEFAULT_PERMISSION_MODULE = 762
const val HOME_LEFT_COFFEE_BOILER_TEMP = 30
const val HOME_RIGHT_COFFEE_BOILER_TEMP = 31
