package com.inno.coffee.utilities

const val INVALID_INT = -1
const val LOCK_AND_CLEAN_TIME = 15
const val VIEW_FAST_CLICK_INTERVAL_TIME = 300
const val DEFAULT_PERMISSION_MODULE = 762
const val HOME_LEFT_COFFEE_BOILER_TEMP = 0
const val HOME_RIGHT_COFFEE_BOILER_TEMP = 0
// 2024/01/01
const val DEFAULT_SYSTEM_TIME = 1704038400000
const val HEAD_INDEX = 0
const val PRODUCT_STOP = 1
const val PRODUCT_RINSE = 4

const val MAKE_DRINK_COMMAND = 100
const val MAKE_DRINK_REPLY_VALUE = 0

const val KEY_HISTORY = "history"
const val HISTORY_VALUE_PRODUCT = "product"
const val HISTORY_VALUE_CLEAN = "clean"
const val HISTORY_VALUE_RINSE = "rinse"
const val HISTORY_VALUE_ERROR = "error"
const val HISTORY_VALUE_SERVICE = "service"

const val PERMISSION_USERNAME = 1
const val PERMISSION_PASSWORD = 2
const val PERMISSION_MAX_INPUT_SIZE = 15
const val PERMISSION_ENTRANCE_REGISTER = 1
const val PERMISSION_ENTRANCE_ACCOUNT_MANAGE = 2
const val PERMISSION_EDIT_USERNAME = 1
const val PERMISSION_EDIT_PASSWORD = 2
const val PERMISSION_EDIT_REMARKS = 3
const val PERMISSION_ROLE_MANAGER = 1
const val PERMISSION_ROLE_EMPLOYEE = 2
const val PERMISSION_KEY_USERNAME = "permission_key_username"

const val FORMULA_PRODUCT_NAME_MAX_SIZE = 20
const val FORMULA_SHOW_LEARN_WATER = 1
const val FORMULA_SHOW_POWDER_TEST = 2

