package com.inno.coffee.utilities

const val INVALID_INT = -1
const val LOCK_AND_CLEAN_TIME = 15
const val VIEW_FAST_CLICK_INTERVAL_TIME = 300
const val DEFAULT_PERMISSION_MODULE = 762
const val HOME_LEFT_COFFEE_BOILER_TEMP = 0
const val HOME_RIGHT_COFFEE_BOILER_TEMP = 0
// 2024/01/01
const val DEFAULT_SYSTEM_TIME = 1704038400000
const val HEAD_INDEX = 0
